name: Publish documentation

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Installing necessary tools
              run: |
                sudo apt-get install doxygen
                sudo apt-get install graphviz
            
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                submodules: 'recursive'
            
            - name: Configure Doxygen with CMake
              run: cmake . -DNTP_ENABLE_GH_DOCS_ONLY=ON

            - name: Generate documentation
              run: doxygen docs/Doxyfile

            - name: Publish generated content to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: doxygen/html
                token: ${{ secrets.ACCESS_TOKEN }}
